image: jimmycuadra/rust:latest
stages:
    - test

test:
    stage: test
    script:
        - rustc -V
        - cargo -V
        - cargo test
    only:
        - master
    tags:
        - docker-engine
    allow_failure: false
